# Import all classes for better IDE support

from pypddl.formalism import ParserOptions

from ..._pytyr.formalism.planning import (
    MutableStaticAtom,
    MutableFluentAtom,
    MutableDerivedAtom,
    MutableStaticLiteral,
    MutableFluentLiteral,
    MutableDerivedLiteral,
    MutableConjunctiveCondition,
    MutableConjunctiveEffect,
    MutableConditionalEffect,
    MutableAction,
)

from ..._pytyr.formalism.planning import (
    Invariant,
    synthesize_invariants,
    ObjectSubstitution,
    TermSubstitution,
    InvariantMatchData,
    InvariantQueryWorkspace,
    InvariantQueryResult,
    InvariantQueryResultMatch,
    InvariantMatcher,
)

from ..._pytyr.formalism.planning import (
    VariableDomain,
    AxiomDomain,
    ConjunctiveConditionDomain,
    ConjunctiveEffectDomain,
    ConditionalEffectDomain,
    ActionDomain,
    TaskVariableDomains,
)

from ..._pytyr.formalism.planning import (
    # Core symbols
    RowIndex,
    Object,
    ObjectIndex,
    ObjectData,
    ActionBindingData,
    AxiomBindingData,
    Variable,
    VariableIndex,
    VariableData,
    ParameterIndex,
    Term,
    TermData,

    StaticPredicateBinding,
    StaticPredicateBindingIndex,
    StaticPredicateBindingData,
    FluentPredicateBinding,
    FluentPredicateBindingIndex,
    FluentPredicateBindingData,
    DerivedPredicateBinding,
    DerivedPredicateBindingIndex,
    DerivedPredicateBindingData,
    StaticFunctionBinding,
    StaticFunctionBindingIndex,
    StaticFunctionBindingData,
    FluentFunctionBinding,
    FluentFunctionBindingIndex,
    FluentFunctionBindingData,
    AuxiliaryFunctionBinding,
    AuxiliaryFunctionBindingIndex,
    AuxiliaryFunctionBindingData,
    ActionBinding,
    ActionBindingIndex,
    ActionBindingData,
    AxiomBinding,
    AxiomBindingIndex,
    AxiomBindingData,

    # Predicates
    StaticPredicate,
    StaticPredicateIndex,
    StaticPredicateData,
    FluentPredicate,
    FluentPredicateIndex,
    FluentPredicateData,
    DerivedPredicate,
    DerivedPredicateIndex,
    DerivedPredicateData,

    # Atoms
    StaticAtom,
    StaticAtomIndex,
    StaticAtomData,
    FluentAtom,
    FluentAtomIndex,
    FluentAtomData,
    DerivedAtom,
    DerivedAtomIndex,
    DerivedAtomData,
    StaticGroundAtom,
    StaticGroundAtomIndex,
    StaticGroundAtomData,
    FluentGroundAtom,
    FluentGroundAtomIndex,
    FluentGroundAtomData,
    DerivedGroundAtom,
    DerivedGroundAtomIndex,
    DerivedGroundAtomData,

    # Literals
    StaticLiteral,
    StaticLiteralIndex,
    StaticLiteralData,
    FluentLiteral,
    FluentLiteralIndex,
    FluentLiteralData,
    DerivedLiteral,
    DerivedLiteralIndex,
    DerivedLiteralData,
    StaticGroundLiteral,
    StaticGroundLiteralIndex,
    StaticGroundLiteralData,
    FluentGroundLiteral,
    FluentGroundLiteralIndex,
    FluentGroundLiteralData,
    DerivedGroundLiteral,
    DerivedGroundLiteralIndex,
    DerivedGroundLiteralData,
    FluentFDRVariable,
    FluentFDRVariableIndex,
    FluentFDRVariableData,
    FDRValue,
    FluentFDRFact,
    FluentFDRFactData,

    # Functions
    StaticFunction,
    StaticFunctionIndex,
    StaticFunctionData,
    FluentFunction,
    FluentFunctionIndex,
    FluentFunctionData,
    AuxiliaryFunction,
    AuxiliaryFunctionIndex,
    AuxiliaryFunctionData,

    # FunctionTerms
    StaticFunctionTerm,
    StaticFunctionTermIndex,
    StaticFunctionTermData,
    FluentFunctionTerm,
    FluentFunctionTermIndex,
    FluentFunctionTermData,
    AuxiliaryFunctionTerm,
    AuxiliaryFunctionTermIndex,
    AuxiliaryFunctionTermData,
    StaticGroundFunctionTerm,
    StaticGroundFunctionTermIndex,
    StaticGroundFunctionTermData,
    FluentGroundFunctionTerm,
    FluentGroundFunctionTermIndex,
    FluentGroundFunctionTermData,
    AuxiliaryGroundFunctionTerm,
    AuxiliaryGroundFunctionTermIndex,
    AuxiliaryGroundFunctionTermData,

    # FunctionTermValues
    StaticGroundFunctionTermValue,
    StaticGroundFunctionTermValueIndex,
    StaticGroundFunctionTermValueData,
    FluentGroundFunctionTermValue,
    FluentGroundFunctionTermValueIndex,
    FluentGroundFunctionTermValueData,
    AuxiliaryGroundFunctionTermValue,
    AuxiliaryGroundFunctionTermValueIndex,
    AuxiliaryGroundFunctionTermValueData,

    # Operators
    UnaryOperatorSub,
    UnaryOperatorSubIndex,
    UnaryOperatorSubData,
    BinaryOperatorAdd,
    BinaryOperatorAddIndex,
    BinaryOperatorAddData,
    BinaryOperatorSub,
    BinaryOperatorSubIndex,
    BinaryOperatorSubData,
    BinaryOperatorMul,
    BinaryOperatorMulIndex,
    BinaryOperatorMulData,
    BinaryOperatorDiv,
    BinaryOperatorDivIndex,
    BinaryOperatorDivData,
    BinaryOperatorEq,
    BinaryOperatorEqIndex,
    BinaryOperatorEqData,
    BinaryOperatorNe,
    BinaryOperatorNeIndex,
    BinaryOperatorNeData,
    BinaryOperatorLe,
    BinaryOperatorLeIndex,
    BinaryOperatorLeData,
    BinaryOperatorLt,
    BinaryOperatorLtIndex,
    BinaryOperatorLtData,
    BinaryOperatorGe,
    BinaryOperatorGeIndex,
    BinaryOperatorGeData,
    BinaryOperatorGt,
    BinaryOperatorGtIndex,
    BinaryOperatorGtData,
    MultiOperatorAdd,
    MultiOperatorAddIndex,
    MultiOperatorAddData,
    MultiOperatorMul,
    MultiOperatorMulIndex,
    MultiOperatorMulData,
    ArithmeticOperator,
    ArithmeticOperatorData,
    BooleanOperator,
    BooleanOperatorData,
    FunctionExpression,
    FunctionExpressionData,

    # Condition
    ConjunctiveCondition,
    ConjunctiveConditionIndex,
    ConjunctiveConditionData,

    # Effects
    FluentNumericEffectAssign,
    FluentNumericEffectAssignIndex,
    FluentNumericEffectAssignData,
    FluentNumericEffectIncrease,
    FluentNumericEffectIncreaseIndex,
    FluentNumericEffectIncreaseData,
    FluentNumericEffectDecrease,
    FluentNumericEffectDecreaseIndex,
    FluentNumericEffectDecreaseData,
    FluentNumericEffectScaleUp,
    FluentNumericEffectScaleUpIndex,
    FluentNumericEffectScaleUpData,
    FluentNumericEffectScaleDown,
    FluentNumericEffectScaleDownIndex,
    FluentNumericEffectScaleDownData,
    AuxiliaryNumericEffectIncrease,
    AuxiliaryNumericEffectIncreaseIndex,
    AuxiliaryNumericEffectIncreaseData,
    FluentNumericEffectOperator,
    FluentNumericEffectOperatorData,
    AuxiliaryNumericEffectOperator,
    AuxiliaryNumericEffectOperatorData,
    ConjunctiveEffect,
    ConjunctiveEffectIndex,
    ConjunctiveEffectData,
    ConditionalEffect,
    ConditionalEffectIndex,
    ConditionalEffectData,

    # Action
    Action,
    ActionIndex,
    ActionData,

    # Axiom
    Axiom,
    AxiomIndex,
    AxiomData,

    # Ground Operators
    GroundUnaryOperatorSub,
    GroundUnaryOperatorSubIndex,
    GroundUnaryOperatorSubData,
    GroundBinaryOperatorAdd,
    GroundBinaryOperatorAddIndex,
    GroundBinaryOperatorAddData,
    GroundBinaryOperatorSub,
    GroundBinaryOperatorSubIndex,
    GroundBinaryOperatorSubData,
    GroundBinaryOperatorMul,
    GroundBinaryOperatorMulIndex,
    GroundBinaryOperatorMulData,
    GroundBinaryOperatorDiv,
    GroundBinaryOperatorDivIndex,
    GroundBinaryOperatorDivData,
    GroundBinaryOperatorEq,
    GroundBinaryOperatorEqIndex,
    GroundBinaryOperatorEqData,
    GroundBinaryOperatorNe,
    GroundBinaryOperatorNeIndex,
    GroundBinaryOperatorNeData,
    GroundBinaryOperatorLe,
    GroundBinaryOperatorLeIndex,
    GroundBinaryOperatorLeData,
    GroundBinaryOperatorLt,
    GroundBinaryOperatorLtIndex,
    GroundBinaryOperatorLtData,
    GroundBinaryOperatorGe,
    GroundBinaryOperatorGeIndex,
    GroundBinaryOperatorGeData,
    GroundBinaryOperatorGt,
    GroundBinaryOperatorGtIndex,
    GroundBinaryOperatorGtData,
    GroundMultiOperatorAdd,
    GroundMultiOperatorAddIndex,
    GroundMultiOperatorAddData,
    GroundMultiOperatorMul,
    GroundMultiOperatorMulIndex,
    GroundMultiOperatorMulData,
    GroundArithmeticOperator,
    GroundArithmeticOperatorData,
    GroundBooleanOperator,
    GroundBooleanOperatorData,
    GroundFunctionExpression,
    GroundFunctionExpressionData,

    # GroundCondition
    GroundConjunctiveCondition,
    GroundConjunctiveConditionIndex,
    GroundConjunctiveConditionData,

    # Ground NumericEffects
    FluentGroundNumericEffectAssign,
    FluentGroundNumericEffectAssignIndex,
    FluentGroundNumericEffectAssignData,
    FluentGroundNumericEffectIncrease,
    FluentGroundNumericEffectIncreaseIndex,
    FluentGroundNumericEffectIncreaseData,
    FluentGroundNumericEffectDecrease,
    FluentGroundNumericEffectDecreaseIndex,
    FluentGroundNumericEffectDecreaseData,
    FluentGroundNumericEffectScaleUp,
    FluentGroundNumericEffectScaleUpIndex,
    FluentGroundNumericEffectScaleUpData,
    FluentGroundNumericEffectScaleDown,
    FluentGroundNumericEffectScaleDownIndex,
    FluentGroundNumericEffectScaleDownData,
    AuxiliaryGroundNumericEffectIncrease,
    AuxiliaryGroundNumericEffectIncreaseIndex,
    AuxiliaryGroundNumericEffectIncreaseData,
    FluentGroundNumericEffectOperator,
    FluentGroundNumericEffectOperatorData,
    AuxiliaryGroundNumericEffectOperator,
    AuxiliaryGroundNumericEffectOperatorData,
    GroundConjunctiveEffect,
    GroundConjunctiveEffectIndex,
    GroundConjunctiveEffectData,
    GroundConditionalEffect,
    GroundConditionalEffectIndex,
    GroundConditionalEffectData,

    # GroundAction
    GroundAction,
    GroundActionIndex,
    GroundActionData,

    # GroundAxiom
    GroundAxiom,
    GroundAxiomIndex,
    GroundAxiomData,

    # Tasks
    Minimize,
    Maximize,
    Metric,
    MetricIndex,
    MetricData,
    Domain,
    DomainIndex,
    DomainData,
    LiftedTask,
    LiftedTaskIndex,
    LiftedTaskData,
    GroundTask,
    GroundTaskIndex,
    GroundTaskData,
    PlanningDomain,
    PlanningTask,
    PlanningFDRTask,

    # Parser
    Parser,

    # Repository
    RepositoryFactory,
    Repository,

    # FDRContext
    FDRContext,
)
