set(PYTYR_STUB_ROOT "${CMAKE_INSTALL_PREFIX}/pytyr")

if(EXISTS "${PYTYR_STUB_ROOT}")
    file(GLOB_RECURSE PYTYR_STUB_FILES "${PYTYR_STUB_ROOT}/*.pyi")

    foreach(PYTYR_STUB_FILE IN LISTS PYTYR_STUB_FILES)
        file(READ "${PYTYR_STUB_FILE}" PYTYR_STUB_CONTENT)
        set(PYTYR_PATCHED_STUB_CONTENT "${PYTYR_STUB_CONTENT}")

        string(REPLACE "pytyr._pytyr." "pytyr." PYTYR_PATCHED_STUB_CONTENT "${PYTYR_PATCHED_STUB_CONTENT}")
        string(REPLACE "pytyr._pytyr" "pytyr" PYTYR_PATCHED_STUB_CONTENT "${PYTYR_PATCHED_STUB_CONTENT}")

        if(NOT PYTYR_STUB_CONTENT STREQUAL PYTYR_PATCHED_STUB_CONTENT)
            file(WRITE "${PYTYR_STUB_FILE}" "${PYTYR_PATCHED_STUB_CONTENT}")
        endif()
    endforeach()
endif()
